### ISSUE TITLE
Add Duration support for Timer

### ISSUE THREAD

**Issue by BCSol** [sosy-lab/java-common-lib#41]
It would be nice if `Timer` intervals could be directly retrieved as `java.time.Duration`.

**Comment by PhilippWendler** [comment]
Right, better integration with `java.time` makes sense.

Unfortunately, `Timer` has lots of methods that return a time interval, so adding a `Duration`-returning method for each of them would clutter the API (we can't use overloads).

There are two easy cases that I will certainly implement:
- Add `TimeSpan.asDuration()`. This will allow calls like `timer.getSumTime().asDuration()`.
- Make `TimeSpan` implement `TemporalAmount`, the same interface that `Duration` also implements. This might make it possible to use `TimeSpan`s directly in some cases where conversion to `Duration` would have been necessary otherwise.

What concrete use cases do you have for timer results as `Duration`, e.g., where do you want to pass such values to? Maybe there is something else that we can do to simplify this.

**Comment by BCSol** [comment]
The main uses cases are:
- accumulating `Duration`s and `TimeSpan`s
- adding `TimeSpan`s to `java.time.Temporal`s like `Instant` and `OffsetDateTime`

Both should be satisfied with the proposed changes.

**Comment by PhilippWendler** [comment]
Published as part of 0.3000-502-gb581f5d.
